name: Visitor Counter
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  visitor_count:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Visitor Count
        id: visitor
        run: |
          VISITORS=$(git rev-list --all --count)
          echo "count=$VISITORS" >> $GITHUB_OUTPUT
          
      - name: Update README with Visitor Count
        run: |
          sed -i '/<!-- VISITS:START -->/,/<!-- VISITS:END -->/c\<!-- VISITS:START -->\n![Visitor Count](https://img.shields.io/badge/Visitors-'"${{ steps.visitor.outputs.count }}"'-blue)\n<!-- VISITS:END -->' README.md
          
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update visitor count" || exit 0
          git push
